//! Deterministic build manifest: a truthful record of one complete build.
//!
//! After every successful build, Signal writes `.signal/manifest.json`
//! describing exactly what went in (semantic inputs) and what came out
//! (artifact bytes). The manifest does not influence the build that writes
//! it; the *next* build consults it to reuse unchanged artifacts and to prune
//! stale outputs. It is disposable build state, not a public artifact: never
//! planned, never served, and deleting `.signal/` changes only how much work
//! the next build does, never its correctness.
//!
//! Design rules:
//! - Flat records, no graph: `artifacts[path]` lists its own inputs; there
//!   are no edges to traverse and no DAG to persist.
//! - Digests hash canonical serializations (structs in field order,
//!   `BTreeMap`s, ordered `Vec`s) — never `Debug`, never `HashMap`
//!   iteration, never timestamps, mtimes, or pointers.
//! - Only digests are stored: the manifest can depend on sensitive config
//!   values without containing them.
//!
//! This module also owns the shared deterministic derivations (template
//! selection, taxonomy roots, feed limits) used by both artifact resolution
//! and manifest recording, so the two can never disagree.

use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};
use signal_core::{
    ArtifactKind, ArtifactSpec, CollectionId, ContentEntry, Route, SignalConfig, SiteModel,
};
use signal_generators::{Home, MainFeed, TaxonomyFeeds, TopicsIndex};
use signal_render::Renderer;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::errors::BuildError;

/// Manifest schema version. Bump deliberately on breaking changes.
pub const MANIFEST_SCHEMA_VERSION: u32 = 1;
/// Build-state directory inside the output root. Never served, never planned.
pub const MANIFEST_DIR: &str = ".signal";
/// Manifest filename inside [`MANIFEST_DIR`].
pub const MANIFEST_FILE: &str = "manifest.json";

/// Deliberately maintained version of Signal's output-generating behavior.
///
/// Bump this whenever a change can alter generated bytes without necessarily
/// changing any recorded semantic input: rendering, Markdown transforms,
/// heading anchors, date formatting, reading time, excerpts, RSS/sitemap
/// serialization, search projection, JSON-LD, default rendering contexts,
/// artifact planning that changes output, or asset behavior.
///
/// Do NOT bump it for comments, refactors with byte-identical output,
/// test-only changes, documentation, or output-preserving performance work.
///
/// This is separate from [`MANIFEST_SCHEMA_VERSION`]: the schema says whether
/// the metadata can be read; this says whether previously generated artifacts
/// are semantically eligible for reuse.
///
/// History: `1` covered generation through slice 15B; `2` adds route-to-URL
/// path encoding (slice 15C), which changes feed, sitemap, search, and
/// template-context bytes for routes with URL-significant characters; `3`
/// extends that encoding to front-matter image `src` values and internal
/// menu URLs (slice 15E), which changes page bytes for images and menus
/// with URL-significant characters; `4` adds the `extra` and `related`
/// context keys, ARIA roles on alerts, the Mermaid `<details>` source
/// fallback, and opt-in Git-derived `last_modified`; `5` adds section and
/// taxonomy-label RSS feeds (new `index.xml` artifacts under `[feed]`),
/// opt-in robots.txt (`[robots]`), and the themed 404 artifact
/// (`site.not_found_template`); `6` adds authored topic display order
/// (`tag_order` in entry digests and template-visible tag lists); `7` adds
/// hero `image`/`image_alt` to entry summaries (home heroes, cards, and
/// every listing/term/related projection that embeds them); `8` adds
/// opt-in HTML minification (`[output] minify_html`), a post-render output
/// step that changes HTML bytes when enabled; `9` adds first-class asset
/// edges (A1): page artifacts name their entry's referenced source assets
/// as `Static` inputs, so asset-byte changes invalidate embedding pages;
/// `10` adds generated image derivatives (A2): `DerivedImage` artifacts
/// and derivative inputs on embedding pages, plus the `[images]`
/// configuration they derive from; `11` adds responsive image rendering
/// (A3): body `<img>` tags and the `responsive_image` hero context embed
/// planned derivatives as `srcset`/`sizes`/dimensions on configured
/// sites (unconfigured output is byte-identical, but rendering semantics
/// changed, so the gate rebuilds once); `12` adds the AVIF derivative
/// format and `<picture>` rendering (A4): the `[images]` format set
/// (`format`/`formats`) joins derivative identity, and multi-format plans
/// render `<source>` groups with a WebP-preferring fallback (single-format
/// output is unchanged in shape, but encoder identity and rendering
/// semantics changed, so the gate rebuilds once); `13` adds generated
/// social cards (A5): `[social]` joins the configuration digest, entry
/// pages on enabled sites gain an `og:image`/`twitter:*` card reference,
/// and `SocialImage` artifacts carry the generator's identity (font,
/// layout, encoder). Disabled sites produce byte-identical output but the
/// config shape changed, so the gate rebuilds once. `14` adds WebP as a
/// valid derivative source: configured sites that reference WebP assets now
/// plan derivatives and consume responsive markup through the existing
/// pipeline. Existing PNG/JPEG and disabled-site output is unchanged, but the
/// additional artifacts and page bytes require a one-time compatibility
/// rebuild for affected sites.
pub const GENERATION_BEHAVIOR_VERSION: u32 = 14;

/// Identity of the code that produced a manifest.
///
/// Both parts participate in the reuse compatibility gate:
/// - `engine_version` is the Cargo package version of the `signal-cli` crate
///   that wrote the manifest (a coarse, released-implementation identity);
/// - `behavior_version` is [`GENERATION_BEHAVIOR_VERSION`], the maintained
///   output-semantics identity.
///
/// The pair is deterministic and carries no machine-specific data. It is a
/// build-wide compatibility condition, never an artifact dependency (it does
/// not appear in any artifact's `inputs`).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GenerationIdentity {
    /// Cargo package version of the Signal implementation.
    pub engine_version: String,
    /// Maintained version of output-generating behavior.
    pub behavior_version: u32,
}

/// The generation identity of the currently running Signal.
pub fn current_generation() -> GenerationIdentity {
    GenerationIdentity {
        engine_version: env!("CARGO_PKG_VERSION").to_string(),
        behavior_version: GENERATION_BEHAVIOR_VERSION,
    }
}

/// Recent entries shown on the home page. Matches the migrated Hugo home
/// grid (`first 8`); a plain cap, not pagination (the site uses none).
pub(crate) const HOME_RECENT_LIMIT: usize = 8;

/// SHA-256 digest rendered as lowercase hex.
///
/// The single digest representation for entries, queries, templates,
/// config, static sources, and outputs. Deterministic, portable, and
/// trivially inspectable.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Digest(String);

impl Digest {
    /// The hex string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for Digest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// SHA-256 over raw bytes (static sources, resolved outputs).
pub fn digest_bytes(bytes: &[u8]) -> Digest {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    Digest(format!("{:x}", hasher.finalize()))
}

/// SHA-256 over a canonical JSON serialization.
///
/// Only pass values with deterministic serialization: structs (field
/// order), `BTreeMap`s (sorted), and `Vec`s in an explicitly deterministic
/// order. Owned serializable data always serializes, so failure here is a
/// bug, not an input error.
pub fn digest_json<T: Serialize>(value: &T) -> Digest {
    let json = serde_json::to_string(value).expect("owned data always serializes");
    digest_bytes(json.as_bytes())
}

/// One semantic input an artifact was resolved from.
///
/// Variants name *what kind* of input, with the key needed to find its
/// digest elsewhere in the manifest (`entries`, `queries`, `templates`) —
/// except `Config`, whose digest is the single `config_digest`, and
/// `Static`, whose source digest equals its artifact's output digest
/// (verbatim passthrough).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum InputRef {
    /// A normalized content entry, keyed by route.
    Entry {
        /// Entry route, e.g. `/posts/alpha/`.
        route: String,
    },
    /// A named projection result, keyed by query key (see query key docs).
    Query {
        /// Query key, e.g. `summaries:posts`.
        key: String,
    },
    /// A template by selected name, e.g. `post.html`.
    ///
    /// Legacy: emitted before slice 14C. Retained so manifests written by
    /// older builds still deserialize; current builds record
    /// [`InputRef::TemplateSet`] instead.
    Template {
        /// Template name.
        name: String,
    },
    /// The complete loaded template set (slice 14C).
    ///
    /// A change to *any* loaded template invalidates every artifact rendered
    /// through templates. This is deliberately coarser than a per-artifact
    /// `{% extends %}` / `{% include %}` closure but is sound, deterministic,
    /// and free of template-source parsing: MiniJinja 2.x caches loaded
    /// templates and exposes no per-render dependency hook, so exact closure
    /// capture would require recompiling the template graph per artifact.
    TemplateSet,
    /// Whole canonical configuration (covers menus, date formats, URLs…).
    Config,
    /// A static source file, relative to `static/`.
    Static {
        /// Source path, e.g. `images/alpha.svg`.
        path: String,
    },
    /// A generated image derivative (A2, ADR 0029), keyed by its full
    /// transformation identity.
    ///
    /// The byte comparison reuses the manifest `assets` source-digest map
    /// (raw form, then percent-decoded form): parameters are part of the
    /// reference itself, so parameter changes surface as `InputsChanged`
    /// while source-byte changes surface as `DerivativeChanged`. A
    /// derivative is never compared against page HTML — the A1 lesson.
    DerivedImage {
        /// Source path relative to `static/`, e.g. `images/hero.jpg`.
        source: String,
        /// Requested output width in pixels.
        width: u32,
        /// Output format name, e.g. `"webp"`.
        format: String,
    },
}

/// One built artifact's record: what it is, what went in, what came out.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactRecord {
    /// Artifact kind, preserved from its spec.
    pub kind: ArtifactKind,
    /// Originating route, if the spec carries one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,
    /// Semantic inputs, in deterministic per-family construction order.
    pub inputs: Vec<InputRef>,
    /// SHA-256 of the exact bytes written.
    pub output_digest: Digest,
}

/// A complete, deterministic description of one successful build.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Manifest {
    /// Schema version ([`MANIFEST_SCHEMA_VERSION`]).
    pub schema_version: u32,
    /// Code identity that produced this manifest.
    ///
    /// `None` only for manifests written before this field existed. Those
    /// remain readable (schema-compatible) but are never eligible for reuse:
    /// generation compatibility is never inferred from the schema version.
    #[serde(default)]
    pub generation: Option<GenerationIdentity>,
    /// Digest of the canonical [`SignalConfig`] serialization.
    pub config_digest: Digest,
    /// Every loaded template by name. Records the full loaded set; since
    /// slice 14C template-rendered artifacts depend on the set as a whole
    /// (`InputRef::TemplateSet`), making `{% extends %}` / `{% include %}`
    /// changes invalidate soundly without a template-source parser.
    pub templates: BTreeMap<String, Digest>,
    /// Every model entry by route.
    pub entries: BTreeMap<String, Digest>,
    /// Every consumed projection by query key.
    pub queries: BTreeMap<String, Digest>,
    /// Every source asset by `static/`-relative path: the digest of its
    /// source bytes (which equals its `Static` artifact's output digest,
    /// verbatim passthrough). `Static` inputs compare against this map,
    /// and so do generated-artifact inputs that consume a source's bytes
    /// (`DerivedImage{source}` and a social image's composited hero) —
    /// always raw-then-decoded, mirroring validation — never against a
    /// referencing artifact's own output digest.
    #[serde(default)]
    pub assets: BTreeMap<String, Digest>,
    /// Every planned artifact by output path.
    pub artifacts: BTreeMap<String, ArtifactRecord>,
}

/// Explicit entry digest input: exactly the normalized fields whose changes
/// can alter generated output.
///
/// `translation_group`, `language`, and `references` are excluded: no
/// current artifact consumes them. Adding such a consumer later must add
/// the field here. `ContentId` is excluded: identity is already carried by
/// collection + source path, and the numeric handle adds nothing semantic.
/// The whole `body` is included — entry HTML, TOC, excerpts, and reading
/// time each consume part of it, and splitting it further would be elegance
/// without a consumer. `extra` is included: entry and section templates can
/// render any of it via the `extra` context key. `tag_order` is included
/// alongside `tags`: reordering terms changes eyebrows and "first topic"
/// picks even when membership is identical.
#[derive(Serialize)]
struct EntryDigestInput<'a> {
    collection: &'a str,
    source_path: &'a str,
    route: &'a str,
    slug: &'a str,
    title: &'a str,
    description: Option<&'a str>,
    date: Option<&'a str>,
    last_modified: Option<&'a str>,
    author: Option<&'a str>,
    image: Option<&'a str>,
    image_alt: Option<&'a str>,
    tags: &'a BTreeSet<String>,
    tag_order: &'a Vec<String>,
    featured: bool,
    section_root: bool,
    body: &'a signal_core::RenderedBody,
    extra: &'a BTreeMap<String, serde_json::Value>,
}

/// Digest one normalized entry.
pub fn entry_digest(entry: &ContentEntry) -> Digest {
    digest_json(&EntryDigestInput {
        collection: &entry.collection.0,
        source_path: &entry.source.relative_path,
        route: &entry.route.0,
        slug: &entry.slug.0,
        title: &entry.title,
        description: entry.description.as_deref(),
        date: entry.date.as_deref(),
        last_modified: entry.last_modified.as_deref(),
        author: entry.author.as_deref(),
        image: entry.image.as_deref(),
        image_alt: entry.image_alt.as_deref(),
        tags: &entry.tags,
        tag_order: &entry.tag_order,
        featured: entry.featured,
        section_root: entry.section_root,
        body: &entry.body,
        extra: &entry.extra,
    })
}

/// Template selected for an entry's collection.
pub(crate) fn template_for_collection(config: &SignalConfig, collection: &str) -> String {
    config
        .collections
        .get(collection)
        .and_then(|c| c.template.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "post.html".to_string())
}

/// Template selected for a collection's section page.
pub(crate) fn section_template_for_collection(config: &SignalConfig, collection: &str) -> String {
    config
        .collections
        .get(collection)
        .and_then(|c| c.section_template.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "section.html".to_string())
}

/// Template selected for the home page.
pub(crate) fn home_template(config: &SignalConfig) -> String {
    config
        .site
        .home_template
        .clone()
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "home.html".to_string())
}

/// Normalized taxonomy root route, e.g. `/topics/`.
pub(crate) fn taxonomy_root(config: &SignalConfig) -> Option<String> {
    config.taxonomy.as_ref().map(|t| {
        TopicsIndex::new(
            t.route_prefix
                .clone()
                .filter(|p| !p.trim().is_empty())
                .unwrap_or_else(|| "/topics/".to_string()),
        )
        .root()
        .to_string()
    })
}

/// Title for the taxonomy index page. Defaults to `Topics`.
pub(crate) fn taxonomy_title(config: &SignalConfig) -> String {
    config
        .taxonomy
        .as_ref()
        .and_then(|t| t.title.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "Topics".to_string())
}

/// Template selected for the taxonomy index page.
pub(crate) fn topics_index_template(config: &SignalConfig) -> String {
    config
        .taxonomy
        .as_ref()
        .and_then(|t| t.index_template.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "topics.html".to_string())
}

/// Template selected for term pages.
pub(crate) fn topic_term_template(config: &SignalConfig) -> String {
    config
        .taxonomy
        .as_ref()
        .and_then(|t| t.term_template.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| "topic.html".to_string())
}

/// Effective feed item cap: configured `[feed] limit`, else the default.
/// Shared by feed resolution and feed digest computation.
pub(crate) fn feed_limit(config: &SignalConfig) -> usize {
    config
        .feed
        .as_ref()
        .and_then(|f| f.limit)
        .filter(|limit| *limit > 0)
        .unwrap_or(signal_core::DEFAULT_FEED_LIMIT)
}

/// Effective related-entry cap: configured `[related] limit`, else the
/// default. Shared by entry contexts and their query digests so the two
/// can never disagree.
pub(crate) fn related_limit(config: &SignalConfig) -> usize {
    config
        .related
        .as_ref()
        .and_then(|r| r.limit)
        .filter(|limit| *limit > 0)
        .unwrap_or(signal_generators::DEFAULT_RELATED_LIMIT)
}

/// Template selected for the themed not-found page, if configured.
///
/// Presence gates the `404.html` artifact; the output path itself is
/// fixed (static hosts resolve unknown paths to `404.html` by convention).
pub(crate) fn not_found_template(config: &SignalConfig) -> Option<String> {
    config
        .site
        .not_found_template
        .clone()
        .filter(|t| !t.trim().is_empty())
}

/// What one RSS output path *is*: the main feed, one collection's section
/// feed, the taxonomy label-index feed, or one term feed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum FeedIdentity {
    /// Site-wide feed at `index.xml`.
    Main,
    /// Feed for the collection with this name, at `<prefix>/index.xml`.
    Section {
        /// Collection name.
        collection: String,
    },
    /// Taxonomy label-index feed at `<root>/index.xml`.
    TaxonomyLabels,
    /// Feed for one term slug at `<root>/<slug>/index.xml`.
    Term {
        /// Term URL slug.
        slug: String,
    },
}

/// Resolve an RSS artifact path to its feed identity from configuration.
///
/// Shared verbatim by artifact resolution and manifest recording, so the
/// two can never disagree about which feed a path is. Precedence: the main
/// feed, then the taxonomy (label-index, then term — checked first so a
/// taxonomy rooted inside a collection prefix still resolves correctly),
/// then collection section feeds. Unknown feed paths are `None` and fail
/// at both use sites.
pub(crate) fn feed_identity(path: &str, config: &SignalConfig) -> Option<FeedIdentity> {
    if path == "index.xml" {
        return Some(FeedIdentity::Main);
    }
    let owner = path.strip_suffix("/index.xml")?;
    if let Some(root) = taxonomy_root(config) {
        let root = root.trim_matches('/');
        if owner == root {
            return Some(FeedIdentity::TaxonomyLabels);
        }
        if let Some(slug) = owner.strip_prefix(root) {
            let slug = slug.strip_prefix('/')?;
            if !slug.is_empty() && !slug.contains('/') {
                return Some(FeedIdentity::Term {
                    slug: slug.to_string(),
                });
            }
        }
    }
    let mut names: Vec<&String> = config.collections.keys().collect();
    names.sort();
    for name in names {
        if config.route_prefix_for(name).trim_matches('/') == owner {
            return Some(FeedIdentity::Section {
                collection: name.clone(),
            });
        }
    }
    None
}

/// Find the collection owning a section route by matching configured route
/// prefixes, falling back to the section-root entry at that route.
pub(crate) fn collection_for_section_route(
    config: &SignalConfig,
    model: &SiteModel,
    route: &Route,
) -> Option<String> {
    let mut names: Vec<&String> = config.collections.keys().collect();
    names.sort();
    for name in names {
        if config.route_prefix_for(name) == route.0 {
            return Some(name.clone());
        }
    }
    model
        .lookup_by_route(route)
        .map(|entry| entry.collection.0.clone())
}

/// Section display title: the section-root entry's title when present,
/// else collection configuration, else the collection name. Shared by the
/// section page context and the section feed channel so HTML listing and
/// feed always agree.
pub(crate) fn section_title(
    config: &SignalConfig,
    model: &SiteModel,
    collection: &str,
    route: &Route,
) -> String {
    model
        .lookup_by_route(route)
        .map(|entry| entry.title.clone())
        .or_else(|| {
            config
                .collections
                .get(collection)
                .and_then(|c| c.title.clone())
        })
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| collection.to_string())
}

/// Query keys name a projection family plus its exact parameters. Families
/// are fixed and disjoint, so concatenation is unambiguous: parameters
/// cannot change the family, and distinct parameters give distinct keys
/// within a family.
pub mod query_key {
    /// `summaries:{collection}` — `collection_summaries` (date-formatted).
    pub fn summaries(collection: &str) -> String {
        format!("summaries:{collection}")
    }
    /// `home:{collection}` — featured pick + recent list.
    pub fn home(collection: &str) -> String {
        format!("home:{collection}")
    }
    /// `topic_terms` — all topic terms with members.
    pub fn topic_terms() -> String {
        "topic_terms".to_string()
    }
    /// `tagged:{label}` — tag members newest-first (exact label).
    pub fn tagged(label: &str) -> String {
        format!("tagged:{label}")
    }
    /// `related:{route}` — capped related-entry summaries for one entry.
    pub fn related(route: &str) -> String {
        format!("related:{route}")
    }
    /// `feed:main` — capped main-feed items.
    pub fn feed_main() -> String {
        "feed:main".to_string()
    }
    /// `feed:section:{collection}` — capped items for one section feed.
    pub fn feed_section(collection: &str) -> String {
        format!("feed:section:{collection}")
    }
    /// `feed:labels` — capped term items for the taxonomy label-index feed.
    pub fn feed_labels() -> String {
        "feed:labels".to_string()
    }
    /// `feed:term:{slug}` — capped items for one term.
    pub fn feed_term(slug: &str) -> String {
        format!("feed:term:{slug}")
    }
    /// `routes_inventory` — sitemap URL set.
    pub fn routes_inventory() -> String {
        "routes_inventory".to_string()
    }
    /// `search_documents` — all search documents.
    pub fn search_documents() -> String {
        "search_documents".to_string()
    }
}

/// Compute one query digest from the exact projection the artifact consumes.
///
/// Summaries are hashed as full projections (title/date/tags/route…), never
/// as bare ID lists: a title edit changes no membership but must change the
/// digest. Date-formatted fields fold `site.date_format` into listing
/// digests, so a format change correctly invalidates listings.
pub(crate) fn digest_query(
    config: &SignalConfig,
    model: &SiteModel,
    key: &str,
) -> Result<Digest, BuildError> {
    use signal_generators as gen;
    let date_format = config.date_format_str();
    let base = config.site.base_url.as_deref().unwrap_or("");
    // Every branch digests the consumed projection value itself.
    if let Some(collection) = key.strip_prefix("summaries:") {
        let summaries = gen::collection_summaries(
            model,
            &CollectionId::new(collection.to_string()),
            date_format,
        );
        return Ok(digest_json(&summaries));
    }
    if let Some(collection) = key.strip_prefix("home:") {
        let home = Home::new(CollectionId::new(collection.to_string()), HOME_RECENT_LIMIT);
        let projection = (
            home.featured(model, date_format),
            home.recent(model, date_format),
        );
        return Ok(digest_json(&projection));
    }
    if key == "topic_terms" {
        let root = taxonomy_root(config).ok_or_else(|| BuildError::Model {
            message: "topic_terms query without taxonomy configuration".to_string(),
        })?;
        let terms = gen::topic_terms(model, &root, date_format).map_err(|e| BuildError::Model {
            message: e.to_string(),
        })?;
        return Ok(digest_json(&terms));
    }
    if let Some(label) = key.strip_prefix("tagged:") {
        return Ok(digest_json(&gen::tagged_summaries(
            model,
            label,
            date_format,
        )));
    }
    if let Some(route) = key.strip_prefix("related:") {
        let entry = model
            .lookup_by_route(&signal_core::Route::new(route.to_string()))
            .ok_or_else(|| BuildError::Model {
                message: format!("no entry for route {route}"),
            })?;
        return Ok(digest_json(&gen::related_entries(
            model,
            entry,
            related_limit(config),
            date_format,
        )));
    }
    if key == "feed:main" {
        return Ok(digest_json(
            &MainFeed::new(feed_limit(config)).items(model, base),
        ));
    }
    if let Some(collection) = key.strip_prefix("feed:section:") {
        let prefix = config.route_prefix_for(collection);
        return Ok(digest_json(
            &signal_generators::SectionFeeds::new(
                CollectionId::new(collection.to_string()),
                prefix,
                feed_limit(config),
            )
            .items(model, base),
        ));
    }
    if key == "feed:labels" {
        let root = taxonomy_root(config).ok_or_else(|| BuildError::Model {
            message: "label feed query without taxonomy configuration".to_string(),
        })?;
        return Ok(digest_json(
            &TaxonomyFeeds::new(root, feed_limit(config)).label_items(model, base),
        ));
    }
    if let Some(slug) = key.strip_prefix("feed:term:") {
        let root = taxonomy_root(config).ok_or_else(|| BuildError::Model {
            message: "term feed query without taxonomy configuration".to_string(),
        })?;
        let terms = gen::topic_terms(model, &root, date_format).map_err(|e| BuildError::Model {
            message: e.to_string(),
        })?;
        let label = terms
            .iter()
            .find(|t| t.slug == slug)
            .map(|t| t.label.clone())
            .ok_or_else(|| BuildError::Model {
                message: format!("no topic with slug {slug:?}"),
            })?;
        let feeds = TaxonomyFeeds::new(root, feed_limit(config));
        return Ok(digest_json(&feeds.term_items(model, &label, base)));
    }
    if key == "routes_inventory" {
        let sections: Vec<String> = {
            let mut names: Vec<&String> = config.collections.keys().collect();
            names.sort();
            names
                .iter()
                .map(|name| config.route_prefix_for(name))
                .collect()
        };
        return Ok(digest_json(&gen::sitemap::sitemap_urls(
            model,
            base,
            config.site.home_collection.is_some(),
            &sections,
            taxonomy_root(config).as_deref(),
        )));
    }
    if key == "search_documents" {
        return Ok(digest_json(&gen::search::search_documents(model)));
    }
    Err(BuildError::Model {
        message: format!("unknown query key {key:?}"),
    })
}

/// Look up a source-asset digest: raw form first, then the
/// percent-decoded form — the precedence `link_check` validates with —
/// so authored encoded references match their on-disk records.
pub(crate) fn asset_digest<'a>(
    assets: &'a BTreeMap<String, Digest>,
    path: &str,
) -> Option<&'a Digest> {
    if let Some(digest) = assets.get(path) {
        return Some(digest);
    }
    match signal_core::percent_decode(path) {
        Some(decoded) if decoded != path => assets.get(&decoded),
        _ => None,
    }
}

/// Canonical digest of the whole configuration (coarse by design).
pub(crate) fn config_digest(config: &SignalConfig) -> Digest {
    digest_json(config)
}

/// Current template digests from the loaded renderer.
pub(crate) fn template_digests(
    renderer: &signal_render::MiniJinjaRenderer,
) -> Result<BTreeMap<String, Digest>, BuildError> {
    let mut templates = BTreeMap::new();
    for name in renderer.template_names() {
        let source = renderer
            .template_source(&name)
            .ok_or_else(|| BuildError::Model {
                message: format!("template {name:?} vanished during build"),
            })?;
        templates.insert(name, digest_bytes(source.as_bytes()));
    }
    Ok(templates)
}

/// Derive one artifact's input references: single source of truth lives in
/// [`crate::build_plan::artifact_inputs`]. Canonical input-list form and
/// per-input digests live there too, so planning (reuse decisions) and
/// recording (the new manifest) share one contract. This wrapper keeps
/// manifest recording compiling against that contract.
fn artifact_inputs(
    spec: &ArtifactSpec,
    config: &SignalConfig,
    model: &SiteModel,
) -> Result<Vec<InputRef>, BuildError> {
    crate::build_plan::artifact_inputs(spec, config, model)
}

/// Build the complete manifest for a finished plan.
///
/// `outputs` maps each spec path to the SHA-256 of its exact written bytes
/// (collected during the resolve/write loop — never re-read, never
/// re-resolved). Every planned spec must have exactly one output digest;
/// every output digest must belong to a planned spec.
pub fn build_manifest(
    config: &SignalConfig,
    model: &SiteModel,
    renderer: &signal_render::MiniJinjaRenderer,
    specs: &[ArtifactSpec],
    outputs: &BTreeMap<String, Digest>,
) -> Result<Manifest, BuildError> {
    if specs.len() != outputs.len() {
        return Err(BuildError::Model {
            message: format!(
                "manifest needs one output digest per spec: {} specs, {} digests",
                specs.len(),
                outputs.len()
            ),
        });
    }
    let mut needed_queries = BTreeSet::new();
    let mut records = BTreeMap::new();
    for spec in specs {
        let output_digest = outputs.get(&spec.path).ok_or_else(|| BuildError::Model {
            message: format!("no output digest for planned artifact {:?}", spec.path),
        })?;
        let inputs = artifact_inputs(spec, config, model)?;
        for input in &inputs {
            if let InputRef::Query { key } = input {
                needed_queries.insert(key.clone());
            }
        }
        if records
            .insert(
                spec.path.clone(),
                ArtifactRecord {
                    kind: spec.kind.clone(),
                    route: spec.route.as_ref().map(|r| r.0.clone()),
                    inputs,
                    output_digest: output_digest.clone(),
                },
            )
            .is_some()
        {
            return Err(BuildError::Model {
                message: format!("duplicate manifest record for {:?}", spec.path),
            });
        }
    }

    let mut queries = BTreeMap::new();
    for key in needed_queries {
        queries.insert(key.clone(), digest_query(config, model, &key)?);
    }
    let mut entries = BTreeMap::new();
    for entry in model.entries() {
        entries.insert(entry.route.0.clone(), entry_digest(entry));
    }
    // Source-asset digests for the `Static` inputs pages and sections
    // name: the output digest of a `Static` artifact IS its source digest
    // (verbatim passthrough), so no source re-read is needed.
    let mut assets = BTreeMap::new();
    for spec in specs {
        if spec.kind == ArtifactKind::Static {
            let digest = outputs.get(&spec.path).ok_or_else(|| BuildError::Model {
                message: format!("no output digest for planned artifact {:?}", spec.path),
            })?;
            assets.insert(spec.path.clone(), digest.clone());
        }
    }

    Ok(Manifest {
        schema_version: MANIFEST_SCHEMA_VERSION,
        generation: Some(current_generation()),
        config_digest: config_digest(config),
        templates: template_digests(renderer)?,
        entries,
        queries,
        assets,
        artifacts: records,
    })
}

/// Previous build state, for reuse decisions.
///
/// The manifest is untrusted metadata: every variant except a fully
/// validated `Usable` manifest leads to a full build, never to reuse.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PreviousManifest {
    /// No manifest file exists: first build.
    Absent,
    /// A manifest exists but must not drive reuse.
    Unusable {
        /// Why: corrupt JSON, unreadable file, unsupported schema, …
        reason: String,
    },
    /// A same-schema manifest whose records may be consulted.
    Usable(Manifest),
}

/// Load the previous manifest without trusting it.
///
/// Missing file → `Absent`. Unreadable file, invalid JSON, or an
/// unsupported `schema_version` → `Unusable` (the build falls back to full;
/// a valid site never fails merely because stale metadata is unusable).
/// Newer schemas are never interpreted as v1.
pub fn load_previous(out_dir: &Path) -> PreviousManifest {
    let path = out_dir.join(MANIFEST_DIR).join(MANIFEST_FILE);
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return PreviousManifest::Absent;
        }
        Err(e) => {
            return PreviousManifest::Unusable {
                reason: format!("cannot read {}: {e}", path.display()),
            };
        }
    };
    let manifest = match parse_manifest(&text) {
        Ok(manifest) => manifest,
        Err(e) => {
            return PreviousManifest::Unusable {
                reason: format!("invalid manifest JSON: {e}"),
            };
        }
    };
    if manifest.schema_version != MANIFEST_SCHEMA_VERSION {
        return PreviousManifest::Unusable {
            reason: format!("unsupported manifest schema {}", manifest.schema_version),
        };
    }
    PreviousManifest::Usable(manifest)
}

/// Whether `prev` was produced by generation behavior compatible with the
/// currently running Signal.
///
/// Note: the existing-output digest helper lives in [`crate::build_plan`]
/// with the rest of the reuse predicate — directories, symlinks, and
/// missing or unreadable files yield `None` (→ rebuild); mtime and size
/// are never trusted, only exact bytes.
///
/// Exact match of both the engine version and the maintained behavior version
/// is required. An absent identity (a manifest written before this field
/// existed) is never compatible: compatibility is not inferred from the
/// schema version. A mismatch is an invalidation condition, not an error.
pub(crate) fn generation_compatible(prev: &Manifest) -> bool {
    prev.generation.as_ref() == Some(&current_generation())
}

/// Manifest JSON text: pretty-printed for reviewability, matching the
/// project's golden-file conventions.
pub fn manifest_json(manifest: &Manifest) -> String {
    serde_json::to_string_pretty(manifest).expect("owned manifest always serializes")
}

/// Read a manifest back (schema round-trips; behavior never branches on it
/// in this slice).
pub fn parse_manifest(text: &str) -> Result<Manifest, String> {
    serde_json::from_str(text).map_err(|e| e.to_string())
}

/// Write the manifest atomically: temp file in `.signal/` plus rename, so a
/// failed write never replaces the previous manifest with a partial one.
pub fn write_manifest(
    out_dir: &Path,
    manifest: &Manifest,
) -> Result<std::path::PathBuf, BuildError> {
    let dir = out_dir.join(MANIFEST_DIR);
    std::fs::create_dir_all(&dir).map_err(|e| BuildError::Write {
        path: dir.display().to_string(),
        message: e.to_string(),
    })?;
    let dest = dir.join(MANIFEST_FILE);
    let temp = dir.join(format!("{MANIFEST_FILE}.tmp"));
    std::fs::write(&temp, manifest_json(manifest)).map_err(|e| BuildError::Write {
        path: temp.display().to_string(),
        message: e.to_string(),
    })?;
    std::fs::rename(&temp, &dest).map_err(|e| BuildError::Write {
        path: dest.display().to_string(),
        message: e.to_string(),
    })?;
    Ok(dest)
}

#[cfg(test)]
mod tests {
    use super::*;
    use signal_core::{CollectionId, ContentId, Slug, SourceRef};

    fn entry(id: u32, collection: &str, slug: &str, title: &str) -> ContentEntry {
        ContentEntry::new(
            ContentId(id),
            CollectionId::new(collection),
            SourceRef::new(CollectionId::new(collection), format!("{slug}.md")),
            Slug::new(slug),
            Route::new(format!("/{collection}/{slug}/")),
            title,
        )
    }

    fn model() -> SiteModel {
        let mut builder = signal_core::SiteModelBuilder::new();
        let mut alpha = entry(1, "posts", "alpha", "Alpha");
        alpha.description = Some("About A.".to_string());
        alpha.date = Some("2026-02-01".to_string());
        alpha.tags.insert("Rust".to_string());
        alpha.body.plain_text = "Alpha body.".to_string();
        builder.add_entry(alpha);
        builder.add_entry(entry(2, "posts", "beta", "Beta"));
        builder.build().expect("builds")
    }

    fn config() -> SignalConfig {
        SignalConfig::from_toml_str(
            "[site]\ntitle = \"T\"\nbase_url = \"https://example.com/\"\n[collections.posts]\nsource = \"content/posts\"\nroute_prefix = \"/posts/\"\n",
        )
        .expect("config parses")
    }

    #[test]
    fn digests_are_stable_hex() {
        let digest = digest_bytes(b"hello");
        assert_eq!(
            digest.as_str(),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
        assert_eq!(digest.to_string(), digest.as_str());
        assert!(digest
            .as_str()
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
    }

    #[test]
    fn identical_inputs_digest_identically() {
        let first = entry_digest(&model().get(ContentId(1)).expect("alpha").clone());
        let second = entry_digest(&model().get(ContentId(1)).expect("alpha").clone());
        assert_eq!(first, second);
        // Struct field order is the canonical form: reordered construction
        // of the same values cannot change the digest.
        assert_eq!(digest_json(&vec!["b", "a"]), digest_json(&vec!["b", "a"]));
    }

    #[test]
    fn entry_digest_tracks_relevant_fields() {
        let base = entry(1, "posts", "alpha", "Alpha");
        let mutate = |mutate: fn(&mut ContentEntry)| {
            let mut entry = base.clone();
            mutate(&mut entry);
            entry_digest(&entry)
        };
        let baseline = entry_digest(&base);
        // Every promoted semantic field participates…
        assert_ne!(baseline, mutate(|e| e.title = "Changed".into()));
        assert_ne!(baseline, mutate(|e| e.description = Some("D".into())));
        assert_ne!(baseline, mutate(|e| e.date = Some("2026-01-01".into())));
        assert_ne!(
            baseline,
            mutate(|e| {
                e.tags.insert("New".into());
            })
        );
        assert_ne!(
            baseline,
            mutate(|e| {
                e.tag_order = vec!["B".into(), "A".into()];
            }),
            "display order is template-visible and must invalidate"
        );
        assert_ne!(baseline, mutate(|e| e.featured = true));
        assert_ne!(
            baseline,
            mutate(|e| e.route = Route::new("/posts/other/".to_string()))
        );
        assert_ne!(baseline, mutate(|e| e.body.plain_text = "other".into()));
        assert_ne!(
            baseline,
            mutate(|e| {
                e.extra.insert(
                    "repo".to_string(),
                    serde_json::Value::String("https://example.com/r".to_string()),
                );
            }),
            "extras are template-visible via the `extra` context key"
        );
        // …while unconsumed semantic fields deliberately do not.
        assert_eq!(
            baseline,
            mutate(|e| e.references.push(ContentId(99))),
            "references are not consumed by any artifact yet"
        );
        assert_eq!(
            baseline,
            mutate(|e| e.language = Some("nl".into())),
            "language is not consumed by any artifact yet"
        );
    }

    #[test]
    fn query_digests_track_projections_not_membership() {
        let first = model();
        let changed_title = {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Renamed");
            alpha.date = Some("2026-02-01".to_string());
            builder.add_entry(alpha);
            builder.add_entry(entry(2, "posts", "beta", "Beta"));
            builder.build().expect("builds")
        };
        // Same membership, different title: the summary digest must move.
        assert_eq!(
            first
                .entries_in_collection(&CollectionId::new("posts"))
                .len(),
            changed_title
                .entries_in_collection(&CollectionId::new("posts"))
                .len()
        );
        assert_ne!(
            digest_query(&config(), &first, "summaries:posts").expect("digest"),
            digest_query(&config(), &changed_title, "summaries:posts").expect("digest")
        );
    }

    #[test]
    fn date_format_changes_listing_digests() {
        let dated = {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Alpha");
            alpha.date = Some("2026-02-01".to_string());
            builder.add_entry(alpha);
            builder.build().expect("builds")
        };
        let other_format = SignalConfig::from_toml_str(
            "[site]\ntitle = \"T\"\ndate_format = \"%-d %B %Y\"\n[collections.posts]\nsource = \"content/posts\"\n",
        )
        .expect("parses");
        // date_formatted flows into EntrySummary, so the digest follows it.
        assert_ne!(
            digest_query(&config(), &dated, "summaries:posts").expect("digest"),
            digest_query(&other_format, &dated, "summaries:posts").expect("digest")
        );
    }

    #[test]
    fn image_changes_move_listing_digests() {
        let build = |image: Option<&str>| {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Alpha");
            alpha.date = Some("2026-02-01".to_string());
            alpha.image = image.map(str::to_string);
            builder.add_entry(alpha);
            builder.add_entry(entry(2, "posts", "beta", "Beta"));
            builder.build().expect("builds")
        };
        let config = config();
        // Heroes and cards render summary images, so adding or changing one
        // must invalidate listings, term pages, and feeds that embed them.
        let baseline = digest_query(&config, &build(None), "summaries:posts").expect("digest");
        let with_image = digest_query(&config, &build(Some("/images/a.png")), "summaries:posts")
            .expect("digest");
        assert_ne!(baseline, with_image);
        assert_ne!(
            with_image,
            digest_query(&config, &build(Some("/images/b.png")), "summaries:posts")
                .expect("digest")
        );
    }

    #[test]
    fn config_digest_tracks_relevant_changes() {
        let baseline = digest_json(&config());
        assert_eq!(baseline, digest_json(&config()));
        let changed = SignalConfig::from_toml_str(
            "[site]\ntitle = \"Other\"\nbase_url = \"https://example.com/\"\n[collections.posts]\nsource = \"content/posts\"\nroute_prefix = \"/posts/\"\n",
        )
        .expect("parses");
        assert_ne!(baseline, digest_json(&changed));
    }

    #[test]
    fn related_query_digest_tracks_other_entries() {
        let build = |beta_tags: &[&str], beta_title: &str| {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Alpha");
            alpha.route = Route::new("/posts/alpha/");
            alpha.tags.insert("Rust".to_string());
            builder.add_entry(alpha);
            let mut beta = entry(2, "posts", "beta", beta_title);
            beta.route = Route::new("/posts/beta/");
            for tag in beta_tags {
                beta.tags.insert(tag.to_string());
            }
            builder.add_entry(beta);
            builder.build().expect("builds")
        };
        let config = config();
        let key = query_key::related("/posts/alpha/");
        // Baseline: beta shares no tag, so nothing is related.
        let baseline = digest_query(&config, &build(&[], "Beta"), &key).expect("digest");
        // Adding a shared tag brings beta into the projection: digest moves.
        let overlapped = digest_query(&config, &build(&["Rust"], "Beta"), &key).expect("digest");
        assert_ne!(baseline, overlapped);
        // Only editing a listed field (title) of a related entry also moves
        // the digest — pages showing the entry must rebuild.
        let renamed =
            digest_query(&config, &build(&["Rust"], "Beta Renamed"), &key).expect("digest");
        assert_ne!(overlapped, renamed);
        // Same model, same digest.
        assert_eq!(
            renamed,
            digest_query(&config, &build(&["Rust"], "Beta Renamed"), &key).expect("digest")
        );
        // Unknown routes are errors, never silent empty digests.
        assert!(digest_query(&config, &build(&["Rust"], "B"), "related:/posts/missing/").is_err());
    }

    #[test]
    fn unknown_query_key_is_an_error() {
        let fixture = model();
        assert!(digest_query(&config(), &fixture, "bogus:key").is_err());
    }

    #[test]
    fn feed_identity_dispatches_every_feed_shape() {
        let cfg = SignalConfig::from_toml_str(
            "[site]\ntitle = \"T\"\nbase_url = \"https://example.com/\"\n[taxonomy]\nroute_prefix = \"/topics/\"\n[feed]\n[collections.posts]\nsource = \"content/posts\"\n",
        )
        .expect("parses");
        assert_eq!(feed_identity("index.xml", &cfg), Some(FeedIdentity::Main));
        assert_eq!(
            feed_identity("posts/index.xml", &cfg),
            Some(FeedIdentity::Section {
                collection: "posts".to_string()
            })
        );
        assert_eq!(
            feed_identity("topics/index.xml", &cfg),
            Some(FeedIdentity::TaxonomyLabels)
        );
        assert_eq!(
            feed_identity("topics/rust/index.xml", &cfg),
            Some(FeedIdentity::Term {
                slug: "rust".to_string()
            })
        );
        // Deeper paths and unknown owners are not feeds.
        assert_eq!(feed_identity("topics/rust/deep/index.xml", &cfg), None);
        assert_eq!(feed_identity("nowhere/index.xml", &cfg), None);
        assert_eq!(feed_identity("posts/index.html", &cfg), None);
    }

    #[test]
    fn feed_identity_prefers_taxonomy_inside_a_collection_prefix() {
        let cfg = SignalConfig::from_toml_str(
            "[site]\ntitle = \"T\"\n[taxonomy]\nroute_prefix = \"/blog/topics/\"\n[collections.blog]\nroute_prefix = \"/blog/\"\n",
        )
        .expect("parses");
        assert_eq!(
            feed_identity("blog/index.xml", &cfg),
            Some(FeedIdentity::Section {
                collection: "blog".to_string()
            })
        );
        assert_eq!(
            feed_identity("blog/topics/index.xml", &cfg),
            Some(FeedIdentity::TaxonomyLabels)
        );
        assert_eq!(
            feed_identity("blog/topics/ai/index.xml", &cfg),
            Some(FeedIdentity::Term {
                slug: "ai".to_string()
            })
        );
    }

    #[test]
    fn section_and_label_feed_digests_track_their_projections() {
        let cfg = SignalConfig::from_toml_str(
            "[site]\ntitle = \"T\"\nbase_url = \"https://example.com/\"\n[taxonomy]\nroute_prefix = \"/topics/\"\n[feed]\n[collections.posts]\nsource = \"content/posts\"\n",
        )
        .expect("parses");
        let base = model();
        let retitled = {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Alpha Renamed");
            alpha.description = Some("About A.".to_string());
            alpha.date = Some("2026-02-01".to_string());
            alpha.tags.insert("Rust".to_string());
            alpha.body.plain_text = "Alpha body.".to_string();
            builder.add_entry(alpha);
            builder.add_entry(entry(2, "posts", "beta", "Beta"));
            builder.build().expect("builds")
        };
        // Section feed: a member's title flows into the items projection.
        let section = "feed:section:posts";
        let baseline = digest_query(&cfg, &base, section).expect("digest");
        assert_ne!(
            baseline,
            digest_query(&cfg, &retitled, section).expect("digest")
        );
        // Label feed: same membership dates and terms ⇒ same digest, even
        // though a member title changed (labels carry term titles/dates).
        let labels = digest_query(&cfg, &base, "feed:labels").expect("digest");
        assert_eq!(
            labels,
            digest_query(&cfg, &retitled, "feed:labels").expect("digest")
        );
        // A new tagged member adds a term: the label digest must move.
        let retagged = {
            let mut builder = signal_core::SiteModelBuilder::new();
            let mut alpha = entry(1, "posts", "alpha", "Alpha");
            alpha.date = Some("2026-02-01".to_string());
            alpha.tags.insert("Rust".to_string());
            alpha.tags.insert("New Term".to_string());
            alpha.body.plain_text = "Alpha body.".to_string();
            builder.add_entry(alpha);
            builder.add_entry(entry(2, "posts", "beta", "Beta"));
            builder.build().expect("builds")
        };
        assert_ne!(
            labels,
            digest_query(&cfg, &retagged, "feed:labels").expect("digest")
        );
    }

    #[test]
    fn stale_detection_is_plan_minus_manifest() {
        use signal_core::{ArtifactKind, ArtifactSpec};
        let prev = Manifest {
            schema_version: MANIFEST_SCHEMA_VERSION,
            generation: None,
            config_digest: digest_bytes(b"cfg"),
            templates: BTreeMap::new(),
            entries: BTreeMap::new(),
            queries: BTreeMap::new(),
            assets: BTreeMap::new(),
            artifacts: BTreeMap::from([
                (
                    "keep/index.html".to_string(),
                    ArtifactRecord {
                        kind: ArtifactKind::Page,
                        route: None,
                        inputs: vec![],
                        output_digest: digest_bytes(b"keep"),
                    },
                ),
                (
                    "gone/index.html".to_string(),
                    ArtifactRecord {
                        kind: ArtifactKind::Page,
                        route: None,
                        inputs: vec![],
                        output_digest: digest_bytes(b"gone"),
                    },
                ),
            ]),
        };
        let specs = vec![ArtifactSpec::new("keep/index.html", ArtifactKind::Page)];
        assert_eq!(
            crate::build_plan::stale_artifact_paths(&prev, &specs),
            vec!["gone/index.html"]
        );
        // Empty plan: everything previously built is stale. Empty manifest:
        // nothing is.
        assert_eq!(
            crate::build_plan::stale_artifact_paths(&prev, &[]),
            vec!["gone/index.html", "keep/index.html"]
        );
        let empty = Manifest {
            artifacts: BTreeMap::new(),
            ..prev.clone()
        };
        assert!(crate::build_plan::stale_artifact_paths(&empty, &specs).is_empty());
    }

    // --- generation identity: reuse compatibility, not schema compatibility ---

    #[test]
    fn generation_identity_is_deterministic_and_serializable() {
        let first = current_generation();
        let second = current_generation();
        assert_eq!(first, second);
        assert_eq!(first.engine_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(first.behavior_version, GENERATION_BEHAVIOR_VERSION);

        let json = serde_json::to_string(&first).expect("serializes");
        let parsed: GenerationIdentity = serde_json::from_str(&json).expect("round-trips");
        assert_eq!(parsed, first);
        // No machine-specific values, paths, or timestamps.
        for forbidden in ["/Users", "/home", "\\", "2026-", "T00:"] {
            assert!(
                !json.contains(forbidden),
                "identity leaked {forbidden:?}: {json}"
            );
        }
    }

    #[test]
    fn generation_compatibility_requires_an_exact_match() {
        let base = Manifest {
            schema_version: MANIFEST_SCHEMA_VERSION,
            generation: Some(current_generation()),
            config_digest: digest_bytes(b"cfg"),
            templates: BTreeMap::new(),
            entries: BTreeMap::new(),
            queries: BTreeMap::new(),
            assets: BTreeMap::new(),
            artifacts: BTreeMap::new(),
        };
        assert!(generation_compatible(&base));

        // Absent identity (legacy manifest) is never compatible.
        let legacy = Manifest {
            generation: None,
            ..base.clone()
        };
        assert!(!generation_compatible(&legacy));

        // A different behavior version or engine version is incompatible.
        let mut other_behavior = current_generation();
        other_behavior.behavior_version += 1;
        assert!(!generation_compatible(&Manifest {
            generation: Some(other_behavior),
            ..base.clone()
        }));
        let mut other_engine = current_generation();
        other_engine.engine_version = "0.0.0-other".to_string();
        assert!(!generation_compatible(&Manifest {
            generation: Some(other_engine),
            ..base.clone()
        }));
    }
}
